#pragma once

#include <samd21.h>

#define FLASH_BOOTLOADER_START 0
#define FLASH_BOOTLOADER_SIZE (8*1024)
#define FLASH_FIRMWARE_START (FLASH_BOOTLOADER_START + FLASH_BOOTLOADER_SIZE)
#define FLASH_FIRMWARE_SIZE (FLASH_SIZE - FLASH_BOOTLOADER_SIZE)